---
title: "ENV 790.30 - Time Series Analysis for Energy Data | Spring 2023"
author: "Katherine Burley"
subtitle: Assignment 1 - Due date 01/24/23
output:
  pdf_document: default
  word_document: default
geometry: margin=2.54cm
---

## Directions

Before making any edits to this file, please rename it such that it includes your first and last name (e.g., "LuanaLima_TSA_A01_Sp23.Rmd")

Once you have this renamed file open in RStudio, the first thing you will do is replace "Student Name" on line 3 with your name. 
Then you will start working through the assignment by  **creating code and output** that answer each question. Be sure to use this assignment document. Your report should contain the answer to each question and any plots/tables you obtained (when applicable).

When you have completed the assignment, **Knit** the text and code into a single PDF file.  Submit this pdf using Sakai. 

## Questions

Q1. What are your previous experiences with time series analysis, R, and Git? 

> Answer: I have a background in economics and previously worked in program evaluation where I frequently used panel and time series data related to energy. However, I have never taken a dedicated time series course and the methods we will use in this course are new to me. I also use R and Git for my current RA position, but I have never used RMarkdown and I'm looking forward to improving my skills through this course.


Q2. (Only if you choose to use git) Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file as instructed on the recorded video "Getting started with Git and Github". 

> Answer: Here is the link to my forked repository: https://github.com/k-burley/TimeSeriesAnalysis_Sp23. Note that I updated my README using the guide on the course GitHub page (https://env790.github.io/docs/modules/readings/git/), since I could not find a video link. 


Q3. For this part we just want to see the path to your R project. No need to do anything. The output will be automatically generated once you knit you file. 

> Answer: This is my working directory:

```{r}
getwd()
```


